import type { Metadata } from "next"
import { createOpenAI } from "@ai-sdk/openai"
import "./globals.css"
import { Inter as FontSans } from "next/font/google"
// import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"
// import ModeToggle from "@/components/ModeToggle"
import NavBar from "@/components/NavBar"

const openai = createOpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
